apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  type: LoadBalancer
  selector:
    app: insurance-app
  ports:
    - name: http
      port: 80          # Toto je verejn√Ω port
      targetPort: 8080  # Toto je port v kontajnery (Spring Boot)

